export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE"
export const DELETE_FLASE_MESSAGE = "DELETE_FLASE_MESSAGE"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const ADD_USER_INPUTDATA = "ADD_USER_INPUTDATA"